from __future__ import annotations

from dataclasses import dataclass


# Population and generation
POPULATION_SIZE_MIN = 8
POPULATION_SIZE_MAX = 12
MUTATION_GENERATIONS_MIN = 3
MUTATION_GENERATIONS_MAX = 5

# Benchmarking
BENCHMARK_RUN_COUNT_MIN = 12
BENCHMARK_RUN_COUNT_MAX = 20
BENCHMARK_WARMUP_RUNS = 2

# Scoring formula coefficients
CV_PENALTY_COEFFICIENT = 0.25
SIZE_PENALTY_COEFFICIENT = 0.05
SYNTHETIC_FALLBACK_SCORE_PENALTY = 0.20

# Stopping criterion
PLATEAU_RATIO_THRESHOLD = 0.10
PLATEAU_ABSOLUTE_FLOOR = 0.005
REQUEST_TIME_BUDGET_MS = 4500
REQUEST_TIME_BUDGET_MAX_MS = 15000

# ValueNet (Phase B+)
VALUENET_INPUT_DIM = 780
EXPLORATION_SLICE_PCT = 0.25
VALUENET_STAGE2_SAMPLE_THRESHOLD = 5000
VALUENET_PRUNING_TARGET_LOW = 0.60
VALUENET_PRUNING_TARGET_HIGH = 0.70
VALUENET_PEARSON_RETRAIN_THRESHOLD = 0.65
VALUENET_PEARSON_ALERT_THRESHOLD = 0.70
VALUENET_FRR_ALERT_THRESHOLD = 0.08
VALUENET_DRIFT_COSINE_THRESHOLD = 0.30
VALUENET_VOLUME_RETRAIN_SAMPLES = 500
VALUENET_LATENCY_WARN_P95_MS = 20
VALUENET_LATENCY_CIRCUIT_BREAK_MS = 50

# Diversity (Phase C+)
DIVERSITY_FAMILY_FLOOR_PCT = 0.15
DIVERSITY_FLOOR_CONSECUTIVE_GENS = 2
DUPLICATE_SIMILARITY_THRESHOLD = 0.95

# Cold-start per-family exploration (Phase C+)
COLD_START_MIN_EVALUATIONS = 75
COLD_START_VALUENET_MULTIPLIER = 1.3
COLD_START_DECAY_EVALUATIONS = 112

# Bottleneck classification (Phase D+)
BOTTLENECK_ELIMINATED_THRESHOLD = 0.20
BOTTLENECK_SHIFTED_DOMINANT_PCT = 0.40

# GRPO (Phase E+)
GRPO_TRAINING_SPLIT_RECENT = 0.80
GRPO_PREREQUISITE_POSITIVE_EXAMPLES = 10000
GRPO_PREREQUISITE_DAYS = 60
GRPO_REWARD_W1_RUNTIME = 0.35
GRPO_REWARD_W2_MEMORY = 0.20
GRPO_REWARD_W3_TEST_PASS = 0.25
GRPO_REWARD_W4_QUALITY = 0.10
GRPO_REWARD_W5_SIZE_PENALTY = 0.05
GRPO_REWARD_W6_CV_PENALTY = 0.05

# Shadow deployment (Phase E+)
SHADOW_TRAFFIC_PCT = 0.10
SHADOW_ROLLBACK_ACCEPTANCE_DROP = 0.05
SHADOW_ROLLBACK_QUALITY_DROP = 0.10
SHADOW_DEPLOYMENT_WINDOW_HOURS = 48

# Phase A request context defaults
PHASE_A_PROMPT_TEMPLATE_VERSION = "phase-a.v1"
PHASE_A_TRANSFORM_LIB_VERSION = "phase-a.transform.v1"
PHASE_A_MAX_SUGGESTIONS = 3

# Optimization tiers (RAEO)
TIER_STANDARD_TIME_BUDGET_MS = 15000
TIER_STANDARD_POP_MIN = 6
TIER_STANDARD_POP_MAX = 8
TIER_STANDARD_MAX_GENERATIONS = 2

TIER_EXTENDED_TIME_BUDGET_MS = 45000
TIER_EXTENDED_POP_MIN = 10
TIER_EXTENDED_POP_MAX = 12
TIER_EXTENDED_MAX_GENERATIONS = 4

TIER_DEEP_TIME_BUDGET_MS = 120000
TIER_DEEP_POP_MIN = 12
TIER_DEEP_POP_MAX = 16
TIER_DEEP_MAX_GENERATIONS = 6

# Transition memory (RAEO)
RAG_RETRIEVAL_LIMIT = 5
RAG_MIN_COMPOSITE_SCORE = 0.05
RAG_SIMILARITY_THRESHOLD = 0.5
RECENCY_WEIGHT_MULTIPLIER = 2.0
RECENCY_WEIGHT_WINDOW_DAYS = 30

# Bandit (RAEO)
BANDIT_PRIOR_MEAN = 0.1
BANDIT_PRIOR_VARIANCE = 0.25
BANDIT_MIN_OBSERVATIONS = 10
BANDIT_MIN_EXPLORATION_RATE = 0.05

# Quality-Diversity archive (RAEO)
QD_IMPROVEMENT_THRESHOLD = -5.0
QD_REGRESSION_THRESHOLD = 0.0

# Multi-generation loop support constants (RAEO)
OFFSPRING_PER_GENERATION = 4
PARENTS_PER_GENERATION = 3
TOURNAMENT_SIZE = 3
TOURNAMENT_SCORE_WEIGHT = 0.7
TOURNAMENT_NOVELTY_WEIGHT = 0.3

# Text feedback (RAEO)
FEEDBACK_MAX_FAILED_ATTEMPTS = 5
FEEDBACK_MAX_HIGH_GAIN_EXAMPLES = 3

# Prompt template registry (RAEO)
PROMPT_TEMPLATE_EFFECTIVENESS_WINDOW_DAYS = 7

# Refinement safety and budgeting (RAEO)
LLM_CALL_OVERHEAD_MS = 1500
REFINEMENT_BUDGET_SAFETY_MARGIN = 1.5
REFINEMENT_MAX_CANDIDATES = 2
REFINEMENT_MIN_TOP_SCORE = 0.0

# Slow-function handling (RAEO)
SLOW_FUNCTION_THRESHOLD_MS = 200
POPULATION_SIZE_SLOW = 4

# Family classifier (RAEO)
FAMILY_CLASSIFICATION_AMBIGUITY_THRESHOLD = 0.20

# Novelty and deduplication (RAEO)
NOVELTY_MAX_REPLACEMENT_ATTEMPTS = 3


@dataclass(frozen=True)
class PhaseAWeights:
    runtime_weight: float = 0.5
    memory_weight: float = 0.3
    quality_weight: float = 0.2
