from __future__ import annotations

from enum import Enum


class FamilyTag(str, Enum):
    DATA_STRUCTURE = "DATA_STRUCTURE"
    LOOP_RESTRUCTURE = "LOOP_RESTRUCTURE"
    VECTORIZATION = "VECTORIZATION"
    CACHING = "CACHING"
    PARALLELIZATION = "PARALLELIZATION"
    ALGORITHMIC = "ALGORITHMIC"
    IO_BATCHING = "IO_BATCHING"
    MEMORY_LAYOUT = "MEMORY_LAYOUT"


class GenerationPath(str, Enum):
    AST_HEURISTIC = "AST_HEURISTIC"
    LLM_TEMPERATURE = "LLM_TEMPERATURE"
    LLM_CRITIQUE_REFINE = "LLM_CRITIQUE_REFINE"


class StoppingReason(str, Enum):
    PLATEAU = "PLATEAU"
    TIME_BUDGET = "TIME_BUDGET"
    MAX_GENERATIONS = "MAX_GENERATIONS"


class BottleneckStatus(str, Enum):
    ELIMINATED = "ELIMINATED"
    SHIFTED = "SHIFTED"
    REDUCED = "REDUCED"
    NO_CHANGE = "NO_CHANGE"


class EvaluationGateResult(str, Enum):
    PASSED = "PASSED"
    FAILED_SYNTAX = "FAILED_SYNTAX"
    FAILED_TESTS = "FAILED_TESTS"
    FAILED_BENCHMARK = "FAILED_BENCHMARK"
    FAILED_CV = "FAILED_CV"
    FAILED_RUN_COUNT = "FAILED_RUN_COUNT"
